---
# Install & Configure Vagrant

- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1

- name: Download vagrant
  get_url: 
    url="{{ vagrant_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/{{ vagrant_version }}.deb"
  when: vagrant_check_deb.rc == 1

- name: Install vagrant
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ vagrant_version }}.deb"
  become: true
  when: vagrant_check_deb.rc == 1