---
# Install & Configure Virtualbox

- name: Add apt package source
  get_url: url=https://www.virtualbox.org/download/oracle_vbox.asc dest=/tmp/vbox.asc

- name:
  command: apt-key add /tmp/vbox.asc
  become: true

- name: Update package manager
  apt: update_cache=yes
  become: true

- name: Install latest virtualbox package
  apt: pkg="virtualbox-5.0" state=present force=yes
  become: true
