---
# Install & Configure Common Tools

- name: Install common tools
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - curl
    - gcc
    - make
    - nmap
    - wget
  become: true
