---
# Install & Configure Dropbox

- name: Check if dropbox is installed
  command: dpkg-query -W dropbox
  register: dropbox_check_deb
  failed_when: dropbox_check_deb.rc > 1
  changed_when: dropbox_check_deb.rc == 1

- name: Download dropbox
  get_url: 
    url="{{ dropbox_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/{{ dropbox_version }}.deb"
  when: dropbox_check_deb.rc == 1

- name: Install dropbox
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ dropbox_version }}.deb"
  become: true
  when: dropbox_check_deb.rc == 1